# Generated by Django 5.2.5 on 2025-11-24 01:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_classes_specialization_courses_subjects_corrections_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='subjects',
            name='semester',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
