# Generated by Django 5.2.5 on 2025-11-24 16:37

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0004_corrections_nb_likes_comments'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='corrections',
            name='users_liked',
            field=models.ManyToManyField(blank=True, related_name='liked_corrections', to=settings.AUTH_USER_MODEL),
        ),
    ]
